# Helper to map Lok Sabha constituencies to states/UTs
# This is based on the Delimitation Commission of India (2008) constituency mapping

class ConstituencyMapping
  STATE_WISE_CONSTITUENCIES = {
    "Andhra Pradesh" => %w[
      AMALAPURAM ANAKAPALLE ANANTAPUR ARAKU CHITTOOR DAHANU GUDUR HINDUPUR KADAPA
      KAKINADA KAKINADA\_RURAL KADIRI KARIMNAGAR KAVATI KOLLAPUR KOTHAPETA
      KURNOOL MACHILIPATNAM NAGARKURNOOL NALGONDA NARASARAOPET NARSAPUR
      ONGOLE PALAKONDA RAJAMPET RAJAHMUNDRY SATHYAVANI SRAVASTI TENALI
      TIRUPATI VIZAG VIZIANAGARAM VIZIANAGARAM WEST GODAVARI YSR KADAPA
    ],

    "Arunachal Pradesh" => %w[ARUNACHAL\_EAST ARUNACHAL\_WEST],

    "Assam" => %w[
      BARPETA DARRANG DHEKIAJULI DIPHU DUBRI GAURIPUR GOALPARA GUWAHATI
      JORHAT KARIMGANJ KOKRAJHAR LAKHIMPUR MAJULI MANGALDAI NAGAON
      NALBARI SIBSAGAR SILCHAR TEZPUR
    ],

    "Bihar" => %w[
      ARA ARAKONAM ARARIA AURANGABAD BAGAHA BAKHTIYARPUR BALLYGUNGE
      BANMANKHI BARH BEGUSARAI BETTIAH BHAGALPUR BHATPAR BHOJPUR
      BIHARSHARIF BUXAR CHANDAULI CHAPRA DARBHANGA GAYA GHAZIPUR GOPALGANJ
      HAJIPUR JAMALPUR JAMUI JEHANABAD JHANJHARPUR KARAKAT KATIHAR KISHANGANJ
      LAKHISARAI MADHUBANI MAHARAJGANJ MAHRAULI MAU MUZAFFARPUR NAWADA
      PATNA SAHIB PATALIPUTRA PURNIA ROSERA SAMASTIPAR SASARAM SITAMARHI
      SIWAN SUPAUL UJIARPUR VAISHALI
    ],

    "Chhattisgarh" => %w[
      BASTAR BILASPUR BILASPUR\_URBAN DHAMTARI JANJGIR\_CHAMPA Kanker KANKER\_SOUTH
      KORBA MAHASAMUND RAIGARH RAIPUR SARANGARH SARGUJA
    ],

    "Delhi" => %w[
      CHANDNI\_CHOWK DELHI\_SADAR\_BAZAR DELHI\_UNIVERSITY EAST\_DELHI
      NEW\_DELHI NORTH\_EAST\_DELHI NORTH\_WEST\_DELHI SOUTH\_DELHI
    ],

    "Goa" => %w[NORTH\_GOA SOUTH\_GOA],

    "Gujarat" => %w[
      AHMEDABAD\_EAST AHMEDABAD\_WEST AMRELI ANAND BANASKANTHA BHARUCH
      BHAVNAGAR CHHOTAUDEPUR DAKOR JAMNAGAR JUNAGADH KHEDA KUTCH
      MEHSANA PATAAN PORBANDAR RAJKOT SABARKANTHA SURENDRANAGAR
      SURAT TAPI VADODARA VALSAD
    ],

    "Haryana" => %w[
      AMBALA\_SC BHIWANI\_MAHENDRAGARH FARIDABAD GURGAON HISAR KARNAL KURUKSHETRA
      ROHTAK SIRSA SONIPAT
    ],

    "Himachal Pradesh" => %w[HAMIRPUR KANGRA MANDI SHIMLA],

    "Jammu & Kashmir" => %w[ANANTNAG BARAMULLA JAMMU SRINAGAR UDHAMPUR],

    "Jharkhand" => %w[
      CHATRA DUMKA DUMKA\_SC GIRIDIH GODDA HAZARIBAGH JAMSHEDPUR KHUNTI
      KODERMA LOHARDAGA PALAMU RAJMAHAL RANCHI SINGHBHUM
    ],

    "Karnataka" => %w[
      BAGALKOT BANGALORE\_CENTRAL BANGALORE\_NORTH BANGALORE\_RURAL
      BANGALORE\_SOUTH BELGAUM BELTHANGADY BELLARY BIDAR CHIKBALLAPUR CHIKKODI
      CHITRADURGA DAKSHINA\_KANNADA DAVANGERE DODDABALLAPUR GULBARGA
      HASSAN Haveri\_Dharwad HUBLI\_Dharwad KOLAR KOPPAL MANDYA MYSORE
      RAICHUR RAYACHOTI SHIMOGA TUMKUR UDUPI CHIKMAGALUR
    ],

    "Kerala" => %w[
      ALAPPUZHA ALATHUR\_SC ATTINGAL CHALAKUDY ERNAKULAM IDUKKI KASARGOD
      KOLLAM KOTTAYAM KOZHIKODE MALAPPURAM Mavelikara PALAKKAD
      PATHANAMTHITTA THIRUVANANTHAPURAM THRISSUR VADAKARA VAYANAD
    ],

    "Madhya Pradesh" => %w[
      AGAR\_MALWA BALAGHAT BALAGHAT\_SC BETUL BHIND BHOPAL BURHANPUR
      CHHINDWARA DAMOH DEWAS DHAULEPUR DINDORI GUNA GWALIOR HOSHANGABAD
      INDORE JABALPUR KHANDWA KHARGONE MANDLA MANDSAUR MORENA
      NARSIMHAPUR NEEMUCH RAISEN REWA SAGAR SATNA SHAJAPUR SIDHI
      TIKAMGARH UJJAIN VIDISHA
    ],

    "Maharashtra" => %w[
      AHMEDNAGAR AKOLA AMRAVATI\_SC AMRAVATI\_SC\_RESERVED AURANGABAD
      BARAMATI BANDRA\_EAST BANDRA\_WEST BHIWANDI BULDHANA CHANDRAPUR
      DHULE GADCHIROLI GONDIA HINGOLI JALNA KANKAVLI KARAD LATUR
      LOK\_SABHA\_CONSTITUENCY\_LIST MALKAPUR MUMBAI\_NORTH\_CENTRAL
      MUMBAI\_NORTH\_EAST MUMBAI\_NORTH\_WEST MUMBAI\_SOUTH\_CENTRAL
      MUMBAI\_SOUTH\_EAST MUMBAI\_SOUTH\_WEST NAGPUR NANDURBAR NASHIK
      OSMANABAD PANDHARPUR\_SC PARBHANI PUNE RAMTEK RATNAGIRI
      SANGAMNER SATARA SHIRUR SOLAPUR THANE WARDHA YAVATMAL
    ],

    "Manipur" => %w[INNER\_MANIPUR OUTER\_MANIPUR],

    "Meghalaya" => %w[SHILLONG TURA],

    "Mizoram" => %w[MIZORAM],

    "Nagaland" => %w[NAGALAND],

    "Odisha" => %w[
      ASKA BALASORE BERHAMPUR BHADRAK BJD\_CANDIDATE\_LIST BOLANGIR
      CUTTACK DHENKANAL JHARSUGUDA JAGATSINGHPUR KALAHANDI KANDHAMAL\_SC
      KEONJHAR KORAPUT KENDRAPARA KENDUJHAR KORAPUT\_ST MAYURBHANJ
      NABARANGPUR\_SC NAYAGARH PURI SAMBALPUR SUNDARGARH
    ],

    "Punjab" => %w[
      ANANDPUR\_SAHIB BATHINDA FATEHGARH\_SAHIB FARIDKOT FEROZEPUR
      GURDASPUR HOSHIARPUR JALANDHAR KAPURTHALA LUDHIANA PATIALA
      SANGRUR TARN\_TARAN
    ],

    "Rajasthan" => %w[
      AJMER ALWAR BANSWARA BARMER BIKANER CHURU DAUSA DHAURPUR DOLPUR
      GANGANAGAR JAIPUR JAIPUR\_RURAL JALORE JHALAWAR JODHPUR KARauli
      KOTA NAGAUR PALI Rajsamand SIKAR SIROHI TONK UDAIPUR
    ],

    "Sikkim" => %w[SIKKIM],

    "Tamil Nadu" => %w[
      ARANI ARANI\_RESERVED ARANI\_SC ARAVAKURICHI CHENNAI\_CENTRAL CHENNAI\_NORTH
      CHENNAI\_SOUTH COIMBATORE CUDDALORE DHARMAPURI DINDIGUL ERODE
      KALLAKURICHI KANYAKUMARI KARUR KRISHNAGIRI MADURAI MAYILADUTHURAI
      NAMAKKAL NAGERCOIL PERAMBALUR POLLACHI RAMANATHAPURAM SALEM
      SIVAGANGA THANJAVUR THENI THOOTHUKUDI TIRUCHIRAPPALLI
      TIRUNELVELI TIRUPATHUR TIRUPPUR TIRUVALLUR TIRUVANNAMALAI TUTICORIN
      VELLORE VILUPPURAM VIRUDHUNAGAR
    ],

    "Telangana" => %w[
      ADILABAD\_ST ALAMPUR BHONGIR CHEVELLA HYDERABAD JAGTIAL
      KARIMNAGAR KHAMMAM MAHBUBNAGAR MANCHERIAL MEDAK MIRYALAGUDA
      NAGARKURNOOL NALGONDA NIZAMABAD PEDDAPALLI SECUNDERABAD
      SIRCILLA WARANGAL ZAHIRABAD
    ],

    "Tripura" => %w[TRIPURA\_EAST TRIPURA\_WEST],

    "Uttar Pradesh" => %w[
      AGRA AKBARPUR ALIGARH AMBEDKAR\_NAGAR AMETHI AMROHA AONLA
      AZAMGARH BAHRAICH BANDA BAREILLY BASTI BADAUN BULANDSHAHR
      CHANDAULI DEOBAND DEORIA DHAULERPUR DOMARIYAGANJ ETAWAH FAIZABAD
      FARRUKHABAD FATEHPUR\_Sikri GAUTAM\_BUDDHA\_NAGAR GHAZIABAD
      GHAZIPUR GHAZIYABAD GONDA HAMIRPUR HARDOI JALAUN JANSATH
      JAUNPUR JHANSI KAIRANA KANNAUJ KANNAUJ\_SC KANPUR KHURJA
      KISHANGANJ KUSHINAGAR LALGANJ LUCKNOW MAHARAJGANJ MAHRAULI
      MAINPARI MAU MIRZAPUR MISRIKH MORADABAD MUNDAI Muzaffarnagar
      NAGINA NAJIBABAD NANPARA PATHERDI PHULPUR PILIBHIT PRATAPGARH
      RAEBARELI RAE\_BARELI RAMPUR SANT\_KABIR\_NAGAR SITAPUR
      SULTANPUR SUWAN THERI UNNAO VARANASI
    ],

    "Uttarakhand" => %w[ALMORA\_SC GARHWAL HARDWAR NAINITAL\_UDDHAM\_SINGH\_NAGAR Pauri\_Garhwal Tehri\_Garhwal],

    "West Bengal" => %w[
      ARAMBAGH ASANSOL BANGAON BARASAT BARRACKPORE BASIRHAT BISHNUPUR
      BOLPUR BURDWAN\_DURGAPUR CALCUTTA\_NORTH CALCUTTA\_SOUTH
      CALCUTTA\_ULUBERIA CANNING\_WEST CHINSURAH DANTAN\_2 DUMDUM
      DIAMOND\_HARBOUR DUMDUM\_SC GHATAL HOWRAH HOOGLY JALPAIGURI
      JHARGRAM KANTHI KOLKATA\_DAKSHIN KOLKATA\_NORTH KOLKATA\_SOUTH
      KOLKATA\_UTTAR KRISHNANAGAR MALDA\_NORTH MALDA\_SOUTH
      MIDNAPORE MURSHIDABAD NADIA\_NORTH\_24\_PARGANAS
      NADIA\_SOUTH\_24\_PARGANAS PARGANAS\_NORTH PARGANAS\_SOUTH
      PURBA\_MEDINIPUR PURLIA\_DARJEELING RAIGANJ RANAGHAT SERAMPORE
      SREERAMPUR SURI\_BIRBHUM TAMLUK ULUBERIA
    ],

    "Andaman and Nicobar Islands" => %w[ANDAMAN\_AND\_NICOBAR],

    "Chandigarh" => %w[CHANDIGARH],

    "Dadra and Nagar Haveli" => %w[DADRA\_AND\_NAGAR\_HAVELI],

    "Daman and Diu" => %w[DAMAN\_AND\_DIU],

    "Lakshadweep" => %w[LAKSHADWEEP],

    "Puducherry" => %w[PUDUCHERRY],

    # Note: Jammu & Kashmir is now divided into J&K and Ladakh
    "Ladakh" => %w[LADAKH]
  }

  def self.state_for_constituency(constituency_name)
    # Clean up the constituency name
    clean_name = constituency_name.upcase.gsub(/[\s\(]+/, '_').gsub(/[\)\s]+/, '').gsub(/_+$/, '')

    STATE_WISE_CONSTITUENCIES.each do |state, constituencies|
      constituencies.each do |const|
        # Try exact match first
        return state if const.upcase.gsub(/_+/, '') == clean_name.gsub(/_+/, '')

        # Try partial match (for reservations like ST, SC)
        const_base = const.upcase.gsub(/_(ST|SC)$/, '').gsub(/_+/, '')
        clean_base = clean_name.gsub(/_(ST|SC)$/, '').gsub(/_+/, '')
        return state if const_base == clean_base
      end
    end

    # If not found, return nil
    nil
  end

  # Test method
  def self.test_mapping
    test_cases = [
      "ADILABAD (ST)",
      "AGRA (SC)",
      "AHMEDABAD EAST",
      "NEW DELHI",
      "MUMBAI SOUTH",
      "CHENNAI CENTRAL"
    ]

    test_cases.each do |const|
      puts "#{const} -> #{state_for_constituency(const)}"
    end
  end
end

# Uncomment to test
# ConstituencyMapping.test_mapping
